### ISSUE TITLE
App Shell

### ISSUE THREAD

**Issue by jdeanwaite** [proinyourpocket/piyp-app#1]
- [x] Create the Firebase project
- [x] Create the code repository
- [x] Create the React Native app shell (should just be able to run the project)
- [x] Create beta builds in both app stores of this blank shell.
- [x] Add FastLane for deployment

The goal here is to just get the shell of the app for both Android and iOS created and in beta so that we have a full end-to-end test and delivery system. Waiting till the end to do this will certainly uncover bugs and unexpected things. Best to do this right off the bat.

**Comment by piypdavid** [comment]
I love being able to see this stuff. Woo hoo!
